### ISSUE TITLE
Infinite loop with Hash1

### ISSUE THREAD

**Issue by briot** [ilanschnell/perfect-hash#4]
Hello,
When I use `generate_code` function on the following keys_hashes list, the generator seems to be taking forever (or perhaps an infinite loop). All parameters are set to default except hft (`trails` is 5, `hft` is 1)

```
[(u'HAS_TRADINGSTATUS', 0), (u'HAS_BID', 1), (u'HAS_ASK', 2), (u'HAS_LASTPRICE', 3), (u'HAS_LASTTRADEQTY', 4), (u'HAS_OPEN', 5), (u'HAS_CLOSE', 6), (u'HAS_HIGH', 7), (u'HAS_LOW', 8), (u'HAS_OCHL_DAILY', 9), (u'HAS_OTHERVALUES', 10), (u'HAS_OPENINGNEXTCALENDARDAY', 11), (u'HAS_CONTEXT', 12), (u'HAS_OFFBOOKTRADE', 13), (u'QUOTATIONUPDATECONTENT_CHANGEBUSINESSDAY', 14), (u'QUOTATIONUPDATECONTENT_SESSION', 15), (u'HAS_RESERVED_16', 16), (u'HAS_RESERVED_17', 17), (u'HAS_RESERVED_18', 18), (u'HAS_RESERVED_19', 19), (u'HAS_RESERVED_20', 20), (u'HAS_RESERVED_21', 21), (u'HAS_RESERVED_22', 22), (u'HAS_RESERVED_23', 23), (u'HAS_RESERVED_24', 24), (u'HAS_RESERVED_25', 25), (u'HAS_RESERVED_26', 26), (u'HAS_RESERVED_27', 27), (u'HAS_RESERVED_28', 28), (u'HAS_RESERVED_29', 29), (u'HAS_RESERVED_30', 30), (u'HAS_RESERVED_31_PRESENCE_MAP', 31)]
```
The algorithm completes when hft is 2 though. The specific entry that seems to cause the issue is `u'QUOTATIONUPDATECONTENT_CHANGEBUSINESSDAY'`

I haven't yet found a workaround.

The traceback is the following, when I interrupt (though of course 
```
  File "perfect-hash/perfect_hash.py", line 442, in generate_code
    f1, f2, G = generate_hash(keyDict(keys_hashes), Hash)
  File "perfect-hash/perfect_hash.py", line 220, in generate_hash
    if G.assign_vertex_values():
  File "perfect-hash/perfect_hash.py", line 158, in assign_vertex_values
    for neighbor, edge_value in self.adjacent[vertex]:
```

Thanks !
Emmanuel

**Comment by ilanschnell** [comment]
Thanks for reporting this problem.  I can reproduce the problem, but I'm not sure what the solution is.

I'm curious to know why you say that you haven't found a workaround yet.  Isn't using hash function type 2 a workaround?

**Comment by ilanschnell** [comment]
I understand what the problem is now.  The problem is the hash function 1.  When the strings get too long, the random salt (that is needed to make each generated hash function different) has no effect.  That is, when the length of the string is roughly more than 30 characters long, the hash value is identical for any randomly initialized hash functions.

The following program shows the problem very clearly:
```
from perfect_hash import Hash1 as Hash

f = Hash(100)
g = Hash(100)

for i in range(1, 35):
    key = 'X' * i
    print(i, f(key), g(key))
```
When you run this program with `Hash2` (instead of `Hash1`) you can see that the two different hash functions continue to give different results even as the size of the key gets very large.

So my advice is to use hash function 2.

**Comment by briot** [comment]
Thanks Ilan,
Using Hash2 is indeed the solution I have chosen. This is part of generated code, and I liked the concept of only generating two integers for T1 and T2 (smaller code size) as opposed to the arrays in Hash2. I was hopping Hash1 could be made to work.

Perhaps worth having some `assert`  in the code to check for key lengths and report warnings ?

In any case, thanks for the analysis here !

Emmanuel

**Comment by ilanschnell** [comment]
I've been playing around with different types of hash functions, and I came up with a very simple one which works for your use case.  Check out the program below:
```
G = [0, 36, 36, 23, 11, 0, 30, 34, 22, 27, 35, 4, 17, 37, 2, 
    8, 26, 36, 20, 25, 9, 15, 21, 13, 4, 20, 6, 0, 0, 0, 0, 6, 19, 28, 0, 
    0, 0, 1, 20]

def hash_f(key, T):
    return sum((T ^ ord(c)) * (i + 1) for i, c in enumerate(str(key))) % 39

def perfect_hash(key):
    return (G[hash_f(key, 95)] + G[hash_f(key, 39)]) % 39

# ============================ Sanity check =============================

K = ["HAS_TRADINGSTATUS", "HAS_BID", "HAS_ASK", 
    "HAS_LASTPRICE", "HAS_LASTTRADEQTY", "HAS_OPEN", "HAS_CLOSE", 
    "HAS_HIGH", "HAS_LOW", "HAS_OCHL_DAILY", "HAS_OTHERVALUES", 
    "HAS_OPENINGNEXTCALENDARDAY", "HAS_CONTEXT", "HAS_OFFBOOKTRADE", 
    "QUOTATIONUPDATECONTENT_CHANGEBUSINESSDAY", 
    "QUOTATIONUPDATECONTENT_SESSION", "HAS_RESERVED_16", "HAS_RESERVED_17", 
    "HAS_RESERVED_18", "HAS_RESERVED_19", "HAS_RESERVED_20", 
    "HAS_RESERVED_21", "HAS_RESERVED_22", "HAS_RESERVED_23", 
    "HAS_RESERVED_24", "HAS_RESERVED_25", "HAS_RESERVED_26", 
    "HAS_RESERVED_27", "HAS_RESERVED_28", "HAS_RESERVED_29", 
    "HAS_RESERVED_30", "HAS_RESERVED_31_PRESENCE_MAP"]

for h, k in enumerate(K):
    assert perfect_hash(k) == h
```
I think this hash function may be too simple to be added to the library, and I'm sure there are many cases where it would fail, but at least it works for your use case, and doesn't require the two additional integer arrays.

**Comment by briot** [comment]
Thanks Ilan,

This is part of a code generator that manipulates all enumeration types in two millions lines
of Ada code (so quite a lot of enumerations). I’ll try it on that use case, that will perhaps
provide useful feedback…

> def hash_f(key, T):
>     return sum((T ^ ord(c)) * (i + 3) for i, c in enumerate(str(key))) % 46

if I understand right, this should become a Hash3 is perfect_hash.py, and then I generate an
equivalent Ada function in my own code ?


Emmanuel

**Comment by ilanschnell** [comment]
Yes, I've added this hash function in the master branch already (including a new example, in `examples/C-3` which shows how to implement the hash function in C.  When you use the master branch, the above code is generated by the command:
```
./perfect-hash --hft=3 --trials=100 keys.txt
```
Where `keys.txt` is a plain text file containing each keyword per line.
Are those keywords likely to change in the future?

**Comment by briot** [comment]
> Are those keywords likely to change in the future?


Probably so.
The idea is the following: users create enumeration types in Ada,
for instance:

```
type Color_Type is (Red, Green, White);
```

Then we pre-process those source files to generate fast input/output functions
so that the identifier `Red` (which maps to 0 in the code) is output as “RED”,
and the input string “RED” results in the Red identifier.
Using the perfect hash has improved performance by a factor of 15 compared to the
built-in implementation of the compiler.

But of course end-users control those enumeration types, and modify them regularly,
so I can’t know in advance whether one day the hash function will stop working or not…

Emmanuel

**Comment by ilanschnell** [comment]
Thanks for giving some more details about how you using this library.  If the end users control the keys, then I would keep using hash function 2.  This hash function has the highest number of random elements when it is created, and is therefore more likely to work with any type of given keys.

I'm not sure how the generated hash functions are used inside the pre-processing of the Ada source files, but if you simply want to map the identifiers to numbers, why not use the Python dictionary?  The perfect hash library is not really meant to replace the Python dictionary in Python.  Instead, its purpose is to find perfect hash functions (for given keys) which then can be easily implemented in other lower level languages, such as C.  This is illustrated by the examples -  you basically create simple standalone C code because you don't want to depend on the Python run-time.  When your program is written in Python already it is much easier, faster and reliable to use the Python dict.

**Comment by briot** [comment]
Sorry, I wasn't clear enough.

The python part is a sort of pre-processor/code generator for the Ada sources.

In Ada, enumerations (like all scalar types) come with two predefined functions named `Image` (which converts from the literal used in the code to its string representation) and `Value` (which does the opposite). The compiler's default implementation traverses a list of string until it find one equal (case-insensitive) to what the user provided, and returns the corresponding literal.

And that's the functions we replaced by using the perfect hash. They are generated from python, but the hashes themselves are only used from Ada (in the python code, you are right that using dict is good enough). So from python and your package we get the integer arrays, that we write into the Ada code where I have the hash functions.

I will keep using Hash2, it seems indeed to have a greater degree of flexibility when the keys are provided by the user and change regularly.

**Comment by ilanschnell** [comment]
Thanks for the clarification.  I understand better now how you are using the perfect hash function.  Basically to work around the compiler's implementation of traversing a list enumerated names until it finds a match each time an item of the list encountered.  It makes complete sense that you are getting about a factor of 15 speedup (when you have about 30 items).

**Comment by ilanschnell** [comment]
Hello Emmanuel,
I just released version 0.3.0, which has a new hash function Hash4 (this one is the default now).  Instead of using the two integer arrays it uses two salt strings.  So for your above keys the generated Python code looks like this:
```
G = [0, 13, 32, 22, 9, 27, 6, 30, 4, 26, 10, 21, 12, 29, 24, 
    29, 23, 1, 4, 13, 17, 0, 28, 25, 1, 22, 23, 11, 2, 5, 14, 20, 30]

def hash_f(key, T):
    return sum(ord(T[i % 40]) * ord(c) for i, c in enumerate(str(key))) % 33

def perfect_hash(key):
    return (G[hash_f(key, "qXQnFCAt2yrVLRoKYXAlUi87AQRmsRR6lfjbpBaX")] +
            G[hash_f(key, "VIMiiWk4bRTyk9jAvC4xJ5vF0ZilFocUQN711Qd3")]) % 33
```
I like the strings better than the integer arrays because the generated code is more concise.  Of course as G has values from 0 to N it would not make sense to try to turn this into a string also.  I've tested Hash4 extensively, that is with many different keys, and didn't find any case that resulted in an infinite loop.  In `examples/C-4` you'll find a C implementation.

**Comment by briot** [comment]
> def hash_f(key, T):
>     return sum(ord(T[i % 40]) * ord(c) for i, c in enumerate(str(key))) % 33
> 
> def perfect_hash(key):
>     return (G[hash_f(key, "qXQnFCAt2yrVLRoKYXAlUi87AQRmsRR6lfjbpBaX")] +
>             G[hash_f(key, "VIMiiWk4bRTyk9jAvC4xJ5vF0ZilFocUQN711Qd3")]) % 33
> 
> I like the strings better than the integer arrays because the generated code is more concise. Of course as G has values from 0 to N it would not make sense to try to turn this into a string also. I've tested Hash4 extensively, that is with many different keys, and didn't find any case that resulted in an infinite loop. In examples/C-4 you'll find a C implementation.

Interesting.
I am not sure, in my case, the string would actually be smaller than the integer array (which really is implemented as just a collection of adjacent bytes in memory), but worth testing.
In terms of performance, the “% 40” seems like a potentially slow operation (that’s a divide after all) compared to the shifts used by Hash1, and the simple lookup in Hash2 ?

Emmanuel

**Comment by ilanschnell** [comment]
The "% 40" is only in the Python code in order to ensure that the string index is not exceeded.  This can be done differently.  For example in my example C-4, this is done using:
```
    for (i = 0; k[i] != '\0' && i < NS; i++) {
        f1 += "qXQnFCAt2yrVLRoKYXAlUi87AQRmsRR6lfjbpBaX"[i] * k[i];
        f2 += "VIMiiWk4bRTyk9jAvC4xJ5vF0ZilFocUQN711Qd3"[i] * k[i];
```
I don't think the `%` operation is lower than `+` or `*`.  Basically Hash4 is still a simple lookup, more precisely indexing into an array, (like Hash2), it just uses a different syntax.

**Comment by briot** [comment]
I tried Hash4, and it also works fine on all my code.
